#!/usr/bin/env bash

cabal update

mkdir -p deps

_project="$(echo *.cabal | cut -d '.' -f 1)"

direct_deps() {
  cat *.cabal | grep ', hw-' | cut -d , -f 2 | cut -d ' ' -f 2 | sort | uniq | grep -v "$_project"
}

pushd deps > /dev/null

cp ../$_project.cabal ./

projects() {
  for x in $(direct_deps | sort | uniq); do
    cabal install $x --dry-run | grep hw- | grep -v "^${_project}-[0-9]\\+\\.[0-9]\\+\\.[0-9]\\+\\.[0-9]\\+$"
  done
}

for x in $(projects | sort | uniq); do
  stack unpack $x
done

rm ./$_project.cabal

popd > /dev/null
