#!/usr/bin/env bash

mkdir -p deps

_project="$(echo *.cabal | cut -d '.' -f 1)"

pushd deps > /dev/null

cp ../$_project.cabal ./

for x in $(cabal install $_project --dry-run | grep hw-); do
  stack unpack $x
done

rm ./$_project.cabal

popd > /dev/null
