#!/usr/bin/env bash

stack query

cabal update

mkdir -p deps

_project="$(cat package.yaml | grep '^name:' | head -n 1 | cut -d : -f 2 | xargs)"

direct_deps() {
  cat ../package.yaml | grep '# \+use-latest-in-ci' | cut -d '#' -f 1 | sed 's|^ *- *||g' | sed 's| .*$||g'
}

pushd deps > /dev/null

cp ../$_project.cabal ./

projects() {
  for x in $(direct_deps | sort | uniq); do
    cabal install $x --dry-run | grep -v "^${_project}-[0-9]\\+\\.[0-9]\\+\\.[0-9]\\+\\.[0-9]\\+$" | tail -n 1
  done
}

if grep '^ *# extra-deps-insertion-point' ../stack.yaml; then
  _indent="$(grep '^ *# extra-deps-insertion-point' ../stack.yaml | head -n 1 | cut -d '#' -f 1 | tr -d '\n')"
  projects | sort | uniq | sed "s|^|$_indent- |g" > stack-b.yaml
  grep '^ *# extra-deps-insertion-point' -B 1000 ../stack.yaml                                              > stack-a.yaml
  grep '^ *# extra-deps-insertion-point' -A 1000 ../stack.yaml | grep -v '^ *# extra-deps-insertion-point'  > stack-c.yaml
else
  cp ../stack.yaml stack-a.yaml
  rm -f stack-b.yaml; touch stack-b.yaml
  echo > stack-c.yaml
fi

cat stack-a.yaml stack-b.yaml stack-c.yaml > ../stack-ci.yaml

popd > /dev/null
