#!/usr/bin/env bash

[ -f ~/.nix-profile/etc/profile.d/nix.sh ] || {
  bash <(curl https://nixos.org/nix/install)
}

. ~/.nix-profile/etc/profile.d/nix.sh

export PATH="~/.cabal/bin:$PATH"

get_buildopts() {
  pushd .. > /dev/null
  [ ! -e hw-buildopts ] && git clone git@github.com:haskell-works/hw-buildopts.git
  popd > /dev/null
}

_repo_name="$(basename `git rev-parse --show-toplevel`)"
_git_short_hash="$(git rev-parse --short HEAD)"
_git_hash="$(git rev-parse HEAD)"

get_buildopts

source_url() {
  _url="$1"
  _content="$(curl --silent --fail "$_url")"

  if [ "$_content" != "" ]; then
    echo "************ Using settings from $_url ************"
    echo   "$_content"
    source /dev/stdin <<< "$_content"
    echo "***************************************************"
    echo ""
  fi
}

source_url "https://raw.githubusercontent.com/haskell-works/hw-buildopts/master/repo/$_repo_name"
source_url "https://raw.githubusercontent.com/haskell-works/hw-buildopts/master/hash/$_git_hash"
source_url "https://raw.githubusercontent.com/haskell-works/hw-buildopts/master/hash/$_git_short_hash"

export LD_LIBRARY_PATH=~/.nix-profile/lib

"$@"
