#!/usr/bin/env bash

if [ "$_system_type" == "Darwin" ]; then
  sed () {
    gsed "$@"
  }
fi

if [ "$HACKAGE_USER" == "" ] || [ "$HACKAGE_PASS" == "" ]; then
  echo "Must supply credentials"
  exit 1
fi

_repo_name=$(basename `git rev-parse --show-toplevel`)
_project="$(cat package.yaml | grep '^name:' | head -n 1 | cut -d : -f 2 | xargs)"
_version="$(cat package.yaml | grep '^version:' | head -n 1 | cut -d : -f 2 | xargs)"

if [ "v$_version" != "$CIRCLE_TAG" ]; then
  echo "Tag mismatch: "v$_version != $CIRCLE_TAG""
  exit 1
fi

cabal configure

cabal sdist

if [ "$ALLOW_UPLOAD" != "" ]; then
  cabal upload \
    --username=$HACKAGE_USER \
    --password=$HACKAGE_PASS \
    "dist/${_project}-${_version}.tar.gz" \
    ${PUBLISH+--publish}
fi
